// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Angle
{
	public static class Degrees
	{
		public static double ToRadians(double value) => value * Math.PI/180.0;
		public static double ToGradians(double value) => value * 200.0/180.0;
		public static double ToMilliradians(double value) => value * 17.4533;
		public static double ToMinuteOfArc(double value) => value * 60.0;
		public static double ToSecondsOfArc(double value) => value * 3600.0;
	}
	public static class Gradians
	{
		public static double ToDegrees(double value) => value * 180.0/200.0;
		public static double ToRadians(double value) => value * Math.PI/200.0;
		public static double ToMilliradians(double value) => value * 15.708;
		public static double ToMinuteOfArc(double value) => value * 54.0;
		public static double ToSecondsOfArc(double value) => value * 3240.0;
	}
	public static class Milliradians
	{
		public static double ToDegrees(double value) => value * 180.0/(1000.0 * Math.PI);
		public static double ToRadians(double value) => value / 1000.0;
		public static double ToGradians(double value) => value * 200.0/(1000.0 * Math.PI);
		public static double ToMinuteOfArc(double value) => value * (60.0 * 180.0)/(1000.0 * Math.PI);
		public static double ToSecondsOfArc(double value) => value * (3600.0 * 180.0)/(1000.0 * Math.PI);
	}
	public static class MinuteOfArc
	{
		public static double ToDegrees(double value) => value / 60.0;
		public static double ToRadians(double value) => value * Math.PI/(60.0 * 180.0);
		public static double ToGradians(double value) => value / 54.0;
		public static double ToMilliradians(double value) => value * (1000.0 * Math.PI) / (60.0 * 180.0);
		public static double ToSecondsOfArc(double value) => value * 60.0;
	}
	public static class Radians
	{
		public static double ToDegrees(double value) => value * 180.0/Math.PI;
		public static double ToGradians(double value) => value * 200.0/Math.PI;
		public static double ToMilliradians(double value) => value * 1000.0;
		public static double ToMinuteOfArc(double value) => value * (60.0 * 180.0)/Math.PI;
		public static double ToSecondsOfArc(double value) => value * (3600.0 * 180.0)/Math.PI;
	}
	public static class SecondsOfArc
	{
		public static double ToDegrees(double value) => value / 3600.0;
		public static double ToRadians(double value) => value * Math.PI/(180.0 * 3600.0);
		public static double ToGradians(double value) => value / 3240.0;
		public static double ToMilliradians(double value) => value * (1000.0 * Math.PI) / (180.0 * 3600.0);
		public static double ToMinuteOfArc(double value) => value / 60.0;
	}
}
