// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Area
{
	public static class Acres
	{
		public static double ToSquareKilometres(double value) => value / 247.105;
		public static double ToSquareMetres(double value) => value * 4046.86;
		public static double ToSquareMiles(double value) => value / 640.0;
		public static double ToSquareYards(double value) => value * 4840.0;
		public static double ToSquareFeet(double value) => value * 43560.0;
		public static double ToSquareInches(double value) => value * 6272640.0;
		public static double ToHectares(double value) => value / 2.471;
	}
	public static class Hectares
	{
		public static double ToSquareKilometres(double value) => value / 100.0;
		public static double ToSquareMetres(double value) => value * 10000.0;
		public static double ToSquareMiles(double value) => value / 259.0;
		public static double ToSquareYards(double value) => value * 11959.900463011;
		public static double ToSquareFeet(double value) => value * 107639.0;
		public static double ToSquareInches(double value) => value * 15500031.0;
		public static double ToAcres(double value) => value * 2.471;
	}
	public static class SquareFeet
	{
		public static double ToSquareKilometres(double value) => value / 10763910.41671;
		public static double ToSquareMetres(double value) => value / 10.764;
		public static double ToSquareMiles(double value) => value / 27878400.0;
		public static double ToSquareYards(double value) => value / 9.0;
		public static double ToSquareInches(double value) => value * 144.0;
		public static double ToHectares(double value) => value / 107639.0;
		public static double ToAcres(double value) => value / 43560.0;
	}
	public static class SquareInches
	{
		public static double ToSquareKilometres(double value) => value / 1550003100.00;
		public static double ToSquareMetres(double value) => value / 1550.0;
		public static double ToSquareMiles(double value) => value / 4014489600.0;
		public static double ToSquareYards(double value) => value / 1296.0;
		public static double ToSquareFeet(double value) => value / 144.0;
		public static double ToHectares(double value) => value / 15500031.0;
		public static double ToAcres(double value) => value / 6272640.0;
	}
	public static class SquareKilometres
	{
		public static double ToSquareMetres(double value) => value * 1e+6;
		public static double ToSquareMiles(double value) => value / 2.58999;
		public static double ToSquareYards(double value) => value * 1195990.05;
		public static double ToSquareFeet(double value) => value * 10763910.41671;
		public static double ToSquareInches(double value) => value * 1550003100.00;
		public static double ToHectares(double value) => value * 100.0;
		public static double ToAcres(double value) => value * 247.105;
	}
	public static class SquareMetres
	{
		public static double ToSquareKilometres(double value) => value / 1e+6;
		public static double ToSquareMiles(double value) => value / 2589988.10;
		public static double ToSquareYards(double value) => value * 1.196;
		public static double ToSquareFeet(double value) => value * 10.764;
		public static double ToSquareInches(double value) => value * 1550.0;
		public static double ToHectares(double value) => value / 10000.0;
		public static double ToAcres(double value) => value / 4046.86;
	}
	public static class SquareMiles
	{
		public static double ToSquareKilometres(double value) => value * 2.58999;
		public static double ToSquareMetres(double value) => value * 2589988.10;
		public static double ToSquareYards(double value) => value * 3097600.0;
		public static double ToSquareFeet(double value) => value * 27878400.0;
		public static double ToSquareInches(double value) => value * 4014489600.0;
		public static double ToHectares(double value) => value * 259.0;
		public static double ToAcres(double value) => value * 640.0;
	}
	public static class SquareYards
	{
		public static double ToSquareKilometres(double value) => value / 1195990.05;
		public static double ToSquareMetres(double value) => value / 1.196;
		public static double ToSquareMiles(double value) => value / 3097600.0;
		public static double ToSquareFeet(double value) => value * 9.0;
		public static double ToSquareInches(double value) => value * 1296.0;
		public static double ToHectares(double value) => value / 11959.900463011;
		public static double ToAcres(double value) => value / 4840.0;
	}
}
