// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units
{
	/// <summary>
	/// Force conversion functions
	/// </summary>
	public static class Force
	{
		/// <summary>
		/// Dynes conversion functions
		/// </summary>
		public static class Dynes
		{
			/// <summary>
			/// Converts the supplied Dynes value to Newtons
			/// </summary>
			/// <param name="value">The Dynes input value</param>
			/// <returns>The value in Newtons</returns>
			public static double ToNewtons(double value) => value / 100000.0;
			/// <summary>
			/// Converts the supplied Dynes value to Poundals
			/// </summary>
			/// <param name="value">The Dynes input value</param>
			/// <returns>The value in Poundals</returns>
			public static double ToPoundals(double value) => value / 13825.4954376;
			/// <summary>
			/// Converts the supplied Dynes value to Kilogram-force
			/// </summary>
			/// <param name="value">The Dynes input value</param>
			/// <returns>The value in Kilogram-force</returns>
			public static double ToKilogramforce(double value) => value / 980665.0;
		}
		/// <summary>
		/// Kilogram-force conversion functions
		/// </summary>
		public static class Kilogramforce
		{
			/// <summary>
			/// Converts the supplied Kilogram-force value to Newtons
			/// </summary>
			/// <param name="value">The Kilogram-force input value</param>
			/// <returns>The value in Newtons</returns>
			public static double ToNewtons(double value) => value * 9.80665;
			/// <summary>
			/// Converts the supplied Kilogram-force value to Dynes
			/// </summary>
			/// <param name="value">The Kilogram-force input value</param>
			/// <returns>The value in Dynes</returns>
			public static double ToDynes(double value) => value * 980665.0;
			/// <summary>
			/// Converts the supplied Kilogram-force value to Poundals
			/// </summary>
			/// <param name="value">The Kilogram-force input value</param>
			/// <returns>The value in Poundals</returns>
			public static double ToPoundals(double value) => value * 70.93163528397;
		}
		/// <summary>
		/// Newtons conversion functions
		/// </summary>
		public static class Newtons
		{
			/// <summary>
			/// Converts the supplied Newtons value to Dynes
			/// </summary>
			/// <param name="value">The Newtons input value</param>
			/// <returns>The value in Dynes</returns>
			public static double ToDynes(double value) => value * 100000.0;
			/// <summary>
			/// Converts the supplied Newtons value to Poundals
			/// </summary>
			/// <param name="value">The Newtons input value</param>
			/// <returns>The value in Poundals</returns>
			public static double ToPoundals(double value) => value * 7.23301;
			/// <summary>
			/// Converts the supplied Newtons value to Kilogram-force
			/// </summary>
			/// <param name="value">The Newtons input value</param>
			/// <returns>The value in Kilogram-force</returns>
			public static double ToKilogramforce(double value) => value / 9.80665;
		}
		/// <summary>
		/// Poundals conversion functions
		/// </summary>
		public static class Poundals
		{
			/// <summary>
			/// Converts the supplied Poundals value to Newtons
			/// </summary>
			/// <param name="value">The Poundals input value</param>
			/// <returns>The value in Newtons</returns>
			public static double ToNewtons(double value) => value / 7.23301;
			/// <summary>
			/// Converts the supplied Poundals value to Dynes
			/// </summary>
			/// <param name="value">The Poundals input value</param>
			/// <returns>The value in Dynes</returns>
			public static double ToDynes(double value) => value * 13825.4954376;
			/// <summary>
			/// Converts the supplied Poundals value to Kilogram-force
			/// </summary>
			/// <param name="value">The Poundals input value</param>
			/// <returns>The value in Kilogram-force</returns>
			public static double ToKilogramforce(double value) => value / 70.93163528397;
		}
	}
}
