// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Frequency
{
	public static class Gigahertz
	{
		public static double ToHertz(double value) => value * 1e+9;
		public static double ToKilohertz(double value) => value * 1e+6;
		public static double ToMegahertz(double value) => value * 1000.0;
	}
	public static class Hertz
	{
		public static double ToKilohertz(double value) => value / 1000.0;
		public static double ToMegahertz(double value) => value / 1e+6;
		public static double ToGigahertz(double value) => value / 1e+9;
	}
	public static class Kilohertz
	{
		public static double ToHertz(double value) => value * 1000.0;
		public static double ToMegahertz(double value) => value / 1000.0;
		public static double ToGigahertz(double value) => value / 1e+6;
	}
	public static class Megahertz
	{
		public static double ToHertz(double value) => value * 1e+6;
		public static double ToKilohertz(double value) => value * 1000.0;
		public static double ToGigahertz(double value) => value / 1000.0;
	}
}
