// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Length
{
	public static class Centimetres
	{
		public static double ToMillimetres(double value) => value * 10.0;
		public static double ToMetres(double value) => value / 100.0;
		public static double ToKilometres(double value) => value / 100000.0;
		public static double ToInches(double value) => value / 2.54;
		public static double ToFeet(double value) => value / 30.48;
		public static double ToYards(double value) => value / 91.44;
		public static double ToMiles(double value) => value / 160934.4;
		public static double ToNauticalMiles(double value) => value / 185200.0;
	}
	public static class Feet
	{
		public static double ToMillimetres(double value) => value * 304.8;
		public static double ToCentimetres(double value) => value * 30.48;
		public static double ToMetres(double value) => value * 0.3048;
		public static double ToKilometres(double value) => value * 0.0003048;
		public static double ToInches(double value) => value * 12.0;
		public static double ToYards(double value) => value / 3.0;
		public static double ToMiles(double value) => value / 5280.0;
		public static double ToNauticalMiles(double value) => value / 6076.12;
	}
	public static class Inches
	{
		public static double ToMillimetres(double value) => value * 25.4;
		public static double ToCentimetres(double value) => value * 2.54;
		public static double ToMetres(double value) => value * 0.0254;
		public static double ToKilometres(double value) => value * 0.0000254;
		public static double ToFeet(double value) => value / 12.0;
		public static double ToYards(double value) => value / 36.0;
		public static double ToMiles(double value) => value / 63360.0;
		public static double ToNauticalMiles(double value) => value / 72913.4;
	}
	public static class Kilometres
	{
		public static double ToMillimetres(double value) => value * 1000000.0;
		public static double ToCentimetres(double value) => value * 100000.0;
		public static double ToMetres(double value) => value * 1000.0;
		public static double ToInches(double value) => value / 0.0000254;
		public static double ToFeet(double value) => value / 0.0003048;
		public static double ToYards(double value) => value / 0.0009144;
		public static double ToMiles(double value) => value / 1.609344;
		public static double ToNauticalMiles(double value) => value / 1.85200;
	}
	public static class Metres
	{
		public static double ToMillimetres(double value) => value * 1000.0;
		public static double ToCentimetres(double value) => value * 100.0;
		public static double ToKilometres(double value) => value / 1000.0;
		public static double ToInches(double value) => value / 0.0254;
		public static double ToFeet(double value) => value / 0.3048;
		public static double ToYards(double value) => value / 0.9144;
		public static double ToMiles(double value) => value / 1609.344;
		public static double ToNauticalMiles(double value) => value / 1852.0;
	}
	public static class Miles
	{
		public static double ToMillimetres(double value) => value * 1609344.0;
		public static double ToCentimetres(double value) => value * 160934.4;
		public static double ToMetres(double value) => value * 1609.344;
		public static double ToKilometres(double value) => value * 1.609344;
		public static double ToInches(double value) => value * 63360.0;
		public static double ToFeet(double value) => value * 5280.0;
		public static double ToYards(double value) => value * 1760.0;
		public static double ToNauticalMiles(double value) => value / 1.15078;
	}
	public static class Millimetres
	{
		public static double ToCentimetres(double value) => value / 10.0;
		public static double ToMetres(double value) => value / 1000.0;
		public static double ToKilometres(double value) => value / 1000000.0;
		public static double ToInches(double value) => value / 25.4;
		public static double ToFeet(double value) => value / 304.8;
		public static double ToYards(double value) => value / 914.4;
		public static double ToMiles(double value) => value / 1609344.0;
		public static double ToNauticalMiles(double value) => value / 1852000.0;
	}
	public static class NauticalMiles
	{
		public static double ToMillimetres(double value) => value * 1852000.0;
		public static double ToCentimetres(double value) => value * 185200.0;
		public static double ToMetres(double value) => value * 1852.0;
		public static double ToKilometres(double value) => value * 1.85200;
		public static double ToInches(double value) => value * 72913.4;
		public static double ToFeet(double value) => value * 6076.12;
		public static double ToYards(double value) => value * 2025.37;
		public static double ToMiles(double value) => value * 1.15078;
	}
	public static class Yards
	{
		public static double ToMillimetres(double value) => value * 914.4;
		public static double ToCentimetres(double value) => value * 91.44;
		public static double ToMetres(double value) => value * 0.9144;
		public static double ToKilometres(double value) => value * 0.0009144;
		public static double ToInches(double value) => value * 36.0;
		public static double ToFeet(double value) => value * 3.0;
		public static double ToMiles(double value) => value / 1760.0;
		public static double ToNauticalMiles(double value) => value / 2025.37;
	}
}
