// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class LuminousEnergy
{
	public static class LumenHour
	{
		public static double ToTalbot(double value) => value * 3600.0;
		public static double ToLumenMinute(double value) => value * 60.0;
		public static double ToLumenSecond(double value) => value * 3600.0;
	}
	public static class LumenMinute
	{
		public static double ToTalbot(double value) => value * 60.0;
		public static double ToLumenHour(double value) => value / 60.0;
		public static double ToLumenSecond(double value) => value * 60.0;
	}
	public static class LumenSecond
	{
		public static double ToTalbot(double value) => value;
		public static double ToLumenHour(double value) => value / 3600.0;
		public static double ToLumenMinute(double value) => value / 60.0;
	}
	public static class Talbot
	{
		public static double ToLumenSecond(double value) => value;
		public static double ToLumenHour(double value) => value / 3600.0;
		public static double ToLumenMinute(double value) => value / 60.0;
	}
}
