// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Mass
{
	public static class Grams
	{
		public static double ToMilligrams(double value) => value * 1000.0;
		public static double ToKilograms(double value) => value / 1000.0;
		public static double ToTonnes(double value) => value * 1e-6;
		public static double ToOunces(double value) => value / 28.3495231;
		public static double ToPounds(double value) => value / 453.59237;
		public static double ToStones(double value) => value / 6350.29318;
	}
	public static class Kilograms
	{
		public static double ToMilligrams(double value) => value * 1e+6;
		public static double ToGrams(double value) => value * 1000.0;
		public static double ToTonnes(double value) => value * 0.001;
		public static double ToOunces(double value) => value * 35.274;
		public static double ToPounds(double value) => value * 2.20462;
		public static double ToStones(double value) => value * 0.157473;
	}
	public static class Milligrams
	{
		public static double ToGrams(double value) => value / 1000.0;
		public static double ToKilograms(double value) => value / 1e+6;
		public static double ToTonnes(double value) => value / 1e+9;
		public static double ToOunces(double value) => value / 28349.5231;
		public static double ToPounds(double value) => value / 453592.37;
		public static double ToStones(double value) => value / 6350293.18;
	}
	public static class Ounces
	{
		public static double ToMilligrams(double value) => value * 28349.5231;
		public static double ToGrams(double value) => value * 28.3495231;
		public static double ToKilograms(double value) => value * 0.0283495;
		public static double ToTonnes(double value) => value * 0.0000283495231;
		public static double ToPounds(double value) => value * 0.0625;
		public static double ToStones(double value) => value * 0.00446429;
	}
	public static class Pounds
	{
		public static double ToMilligrams(double value) => value * 453592.37;
		public static double ToGrams(double value) => value * 453.59237;
		public static double ToKilograms(double value) => value * 0.453592;
		public static double ToTonnes(double value) => value / 2204.62;
		public static double ToOunces(double value) => value * 16.0;
		public static double ToStones(double value) => value / 14.0;
	}
	public static class Stones
	{
		public static double ToMilligrams(double value) => value * 6350293.18;
		public static double ToGrams(double value) => value * 6350.29318;
		public static double ToKilograms(double value) => value * 6.35029;
		public static double ToTonnes(double value) => value * 0.00635029;
		public static double ToOunces(double value) => value * 224.0;
		public static double ToPounds(double value) => value * 14.0;
	}
	public static class Tonnes
	{
		public static double ToMilligrams(double value) => value * 1e+9;
		public static double ToGrams(double value) => value * 1e+6;
		public static double ToKilograms(double value) => value * 1000.0;
		public static double ToOunces(double value) => value / 0.0000283495231;
		public static double ToPounds(double value) => value * 2204.62;
		public static double ToStones(double value) => value * 157.473;
	}
}
