// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units
{
	/// <summary>
	/// Speed conversion functions
	/// </summary>
	public static class Speed
	{
		/// <summary>
		/// Feet Per Second conversion functions
		/// </summary>
		public static class FeetPerSecond
		{
			/// <summary>
			/// Converts the supplied Feet Per Second value to Miles Per Hour
			/// </summary>
			/// <param name="value">The Feet Per Second input value</param>
			/// <returns>The value in Miles Per Hour</returns>
			public static double ToMilesPerHour(double value) => value / 1.46667;
			/// <summary>
			/// Converts the supplied Feet Per Second value to Kilometres Per Hour
			/// </summary>
			/// <param name="value">The Feet Per Second input value</param>
			/// <returns>The value in Kilometres Per Hour</returns>
			public static double ToKilometresPerHour(double value) => value * 1.09728;
			/// <summary>
			/// Converts the supplied Feet Per Second value to Metres Per Second
			/// </summary>
			/// <param name="value">The Feet Per Second input value</param>
			/// <returns>The value in Metres Per Second</returns>
			public static double ToMetresPerSecond(double value) => value / 3.28084;
			/// <summary>
			/// Converts the supplied Feet Per Second value to Knots
			/// </summary>
			/// <param name="value">The Feet Per Second input value</param>
			/// <returns>The value in Knots</returns>
			public static double ToKnots(double value) => value / 1.68781;
		}
		/// <summary>
		/// Kilometres Per Hour conversion functions
		/// </summary>
		public static class KilometresPerHour
		{
			/// <summary>
			/// Converts the supplied Kilometres Per Hour value to Miles Per Hour
			/// </summary>
			/// <param name="value">The Kilometres Per Hour input value</param>
			/// <returns>The value in Miles Per Hour</returns>
			public static double ToMilesPerHour(double value) => value / 1.60934;
			/// <summary>
			/// Converts the supplied Kilometres Per Hour value to Feet Per Second
			/// </summary>
			/// <param name="value">The Kilometres Per Hour input value</param>
			/// <returns>The value in Feet Per Second</returns>
			public static double ToFeetPerSecond(double value) => value / 1.09728;
			/// <summary>
			/// Converts the supplied Kilometres Per Hour value to Metres Per Second
			/// </summary>
			/// <param name="value">The Kilometres Per Hour input value</param>
			/// <returns>The value in Metres Per Second</returns>
			public static double ToMetresPerSecond(double value) => value / 3.6;
			/// <summary>
			/// Converts the supplied Kilometres Per Hour value to Knots
			/// </summary>
			/// <param name="value">The Kilometres Per Hour input value</param>
			/// <returns>The value in Knots</returns>
			public static double ToKnots(double value) => value / 1.852;
		}
		/// <summary>
		/// Knots conversion functions
		/// </summary>
		public static class Knots
		{
			/// <summary>
			/// Converts the supplied Knots value to Miles Per Hour
			/// </summary>
			/// <param name="value">The Knots input value</param>
			/// <returns>The value in Miles Per Hour</returns>
			public static double ToMilesPerHour(double value) => value * 1.15078;
			/// <summary>
			/// Converts the supplied Knots value to Kilometres Per Hour
			/// </summary>
			/// <param name="value">The Knots input value</param>
			/// <returns>The value in Kilometres Per Hour</returns>
			public static double ToKilometresPerHour(double value) => value * 1.852;
			/// <summary>
			/// Converts the supplied Knots value to Feet Per Second
			/// </summary>
			/// <param name="value">The Knots input value</param>
			/// <returns>The value in Feet Per Second</returns>
			public static double ToFeetPerSecond(double value) => value * 1.68781;
			/// <summary>
			/// Converts the supplied Knots value to Metres Per Second
			/// </summary>
			/// <param name="value">The Knots input value</param>
			/// <returns>The value in Metres Per Second</returns>
			public static double ToMetresPerSecond(double value) => value / 1.94384;
		}
		/// <summary>
		/// Metres Per Second conversion functions
		/// </summary>
		public static class MetresPerSecond
		{
			/// <summary>
			/// Converts the supplied Metres Per Second value to Miles Per Hour
			/// </summary>
			/// <param name="value">The Metres Per Second input value</param>
			/// <returns>The value in Miles Per Hour</returns>
			public static double ToMilesPerHour(double value) => value * 2.23694;
			/// <summary>
			/// Converts the supplied Metres Per Second value to Kilometres Per Hour
			/// </summary>
			/// <param name="value">The Metres Per Second input value</param>
			/// <returns>The value in Kilometres Per Hour</returns>
			public static double ToKilometresPerHour(double value) => value * 3.6;
			/// <summary>
			/// Converts the supplied Metres Per Second value to Feet Per Second
			/// </summary>
			/// <param name="value">The Metres Per Second input value</param>
			/// <returns>The value in Feet Per Second</returns>
			public static double ToFeetPerSecond(double value) => value * 3.28084;
			/// <summary>
			/// Converts the supplied Metres Per Second value to Knots
			/// </summary>
			/// <param name="value">The Metres Per Second input value</param>
			/// <returns>The value in Knots</returns>
			public static double ToKnots(double value) => value * 1.94384;
		}
		/// <summary>
		/// Miles Per Hour conversion functions
		/// </summary>
		public static class MilesPerHour
		{
			/// <summary>
			/// Converts the supplied Miles Per Hour value to Kilometres Per Hour
			/// </summary>
			/// <param name="value">The Miles Per Hour input value</param>
			/// <returns>The value in Kilometres Per Hour</returns>
			public static double ToKilometresPerHour(double value) => value * 1.60934;
			/// <summary>
			/// Converts the supplied Miles Per Hour value to Feet Per Second
			/// </summary>
			/// <param name="value">The Miles Per Hour input value</param>
			/// <returns>The value in Feet Per Second</returns>
			public static double ToFeetPerSecond(double value) => value * 1.46667;
			/// <summary>
			/// Converts the supplied Miles Per Hour value to Metres Per Second
			/// </summary>
			/// <param name="value">The Miles Per Hour input value</param>
			/// <returns>The value in Metres Per Second</returns>
			public static double ToMetresPerSecond(double value) => value / 2.23694;
			/// <summary>
			/// Converts the supplied Miles Per Hour value to Knots
			/// </summary>
			/// <param name="value">The Miles Per Hour input value</param>
			/// <returns>The value in Knots</returns>
			public static double ToKnots(double value) => value / 1.15078;
		}
	}
}
