// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Time
{
	public static class Centuries
	{
		public static double ToSeconds(double value) => value * 3.154e+9;
		public static double ToMinutes(double value) => value * 5.256e+7;
		public static double ToHours(double value) => value * 876000.0;
		public static double ToDays(double value) => value * 36500.0;
		public static double ToWeeks(double value) => value * 5214.0;
		public static double ToMonths(double value) => value * 1200.0;
		public static double ToYears(double value) => value * 100.0;
		public static double ToDecades(double value) => value * 10.0;
	}
	public static class Days
	{
		public static double ToSeconds(double value) => value * 86400.0;
		public static double ToMinutes(double value) => value * 1440.0;
		public static double ToHours(double value) => value * 24.0;
		public static double ToWeeks(double value) => value / 7.0;
		public static double ToMonths(double value) => value / 30.417;
		public static double ToYears(double value) => value / 365.0;
		public static double ToDecades(double value) => value / 3650.0;
		public static double ToCenturies(double value) => value / 36500.0;
	}
	public static class Decades
	{
		public static double ToSeconds(double value) => value * 3.154e+8;
		public static double ToMinutes(double value) => value * 5.256e+6;
		public static double ToHours(double value) => value * 87600.0;
		public static double ToDays(double value) => value * 3650.0;
		public static double ToWeeks(double value) => value * 521.0;
		public static double ToMonths(double value) => value * 120.0;
		public static double ToYears(double value) => value * 10.0;
		public static double ToCenturies(double value) => value / 10.0;
	}
	public static class Hours
	{
		public static double ToSeconds(double value) => value * 3600.0;
		public static double ToMinutes(double value) => value * 60.0;
		public static double ToDays(double value) => value / 24.0;
		public static double ToWeeks(double value) => value / 168.0;
		public static double ToMonths(double value) => value / 730.0;
		public static double ToYears(double value) => value / 8760.0;
		public static double ToDecades(double value) => value / 87600.0;
		public static double ToCenturies(double value) => value / 876000.0;
	}
	public static class Minutes
	{
		public static double ToSeconds(double value) => value * 60.0;
		public static double ToHours(double value) => value / 60.0;
		public static double ToDays(double value) => value / 1440.0;
		public static double ToWeeks(double value) => value / 10080.0;
		public static double ToMonths(double value) => value / 43800.0;
		public static double ToYears(double value) => value / 525600.0;
		public static double ToDecades(double value) => value / 5.256e+6;
		public static double ToCenturies(double value) => value / 5.256e+7;
	}
	public static class Months
	{
		public static double ToSeconds(double value) => value * 2.628e+6;
		public static double ToMinutes(double value) => value * 43800.0;
		public static double ToHours(double value) => value * 730.0;
		public static double ToDays(double value) => value * 30.417;
		public static double ToWeeks(double value) => value * 4.345;
		public static double ToYears(double value) => value / 12.0;
		public static double ToDecades(double value) => value / 120.0;
		public static double ToCenturies(double value) => value / 1200.0;
	}
	public static class Seconds
	{
		public static double ToMinutes(double value) => value / 60.0;
		public static double ToHours(double value) => value / 3600.0;
		public static double ToDays(double value) => value / 86400.0;
		public static double ToWeeks(double value) => value / 604800.0;
		public static double ToMonths(double value) => value / 2.628e+6;
		public static double ToYears(double value) => value / 3.1536e+7;
		public static double ToDecades(double value) => value / 3.154e+8;
		public static double ToCenturies(double value) => value / 3.154e+9;
	}
	public static class Weeks
	{
		public static double ToSeconds(double value) => value * 604800.0;
		public static double ToMinutes(double value) => value * 10080.0;
		public static double ToHours(double value) => value * 168.0;
		public static double ToDays(double value) => value * 7.0;
		public static double ToMonths(double value) => value / 4.345;
		public static double ToYears(double value) => value / 52.143;
		public static double ToDecades(double value) => value / 521.0;
		public static double ToCenturies(double value) => value / 5214.0;
	}
	public static class Years
	{
		public static double ToSeconds(double value) => value * 3.1536e+7;
		public static double ToMinutes(double value) => value * 525600.0;
		public static double ToHours(double value) => value * 8760.0;
		public static double ToDays(double value) => value * 365.0;
		public static double ToWeeks(double value) => value * 52.143;
		public static double ToMonths(double value) => value * 12.0;
		public static double ToDecades(double value) => value / 10.0;
		public static double ToCenturies(double value) => value / 100.0;
	}
}
