// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace PutridParrot.Units;

public static class Volume
{
	public static class FluidOunces
	{
		public static double ToMillilitres(double value) => value * 28.413074243749994496;
		public static double ToLitres(double value) => value * 0.028413074243749994496;
		public static double ToKilolitres(double value) => value * 0.000028413074243749994;
		public static double ToTeaspoons(double value) => value * 4.8;
		public static double ToTablespoons(double value) => value * 1.6;
		public static double ToQuarts(double value) => value / 40.0;
		public static double ToPints(double value) => value / 20.0;
		public static double ToGallons(double value) => value / 160.0;
		public static double ToUSTeaspoons(double value) => value / 0.1734737167638313984;
		public static double ToUSTablespoons(double value) => value / 0.52042115029149417472;
		public static double ToUSQuarts(double value) => value / 33.306953618655629312;
		public static double ToUSPints(double value) => value / 16.653476809327814656;
		public static double ToUSGallons(double value) => value / 133.22781447462252544;
		public static double ToUSFluidOunces(double value) => value / 1.0408423005829883904;
		public static double ToUSCups(double value) => value / 8.3267384046639071232;
	}
	public static class Gallons
	{
		public static double ToMillilitres(double value) => value * 4546.091879;
		public static double ToLitres(double value) => value * 4.546091879;
		public static double ToKilolitres(double value) => value * 0.004546091879;
		public static double ToTeaspoons(double value) => value * 768.0;
		public static double ToTablespoons(double value) => value * 256.0;
		public static double ToQuarts(double value) => value * 4.0;
		public static double ToPints(double value) => value * 8.0;
		public static double ToFluidOunces(double value) => value * 160.0;
		public static double ToUSTeaspoons(double value) => value / 0.00108421072977394606;
		public static double ToUSTablespoons(double value) => value / 0.003252632189321838592;
		public static double ToUSQuarts(double value) => value / 0.20816846011659767808;
		public static double ToUSPints(double value) => value / 0.10408423005829883904;
		public static double ToUSGallons(double value) => value / 0.83267384046639071232;
		public static double ToUSFluidOunces(double value) => value / 0.006505264378643677184;
		public static double ToUSCups(double value) => value / 0.052042115029149417472;
	}
	public static class Kilolitres
	{
		public static double ToMillilitres(double value) => value * 1000000.0;
		public static double ToLitres(double value) => value * 1000.0;
		public static double ToTeaspoons(double value) => value / 0.000005919390467447916;
		public static double ToTablespoons(double value) => value / 0.000017758171402343747;
		public static double ToQuarts(double value) => value / 0.00113652296975;
		public static double ToPints(double value) => value / 0.000568261484874999889;
		public static double ToGallons(double value) => value / 0.0045460918799;
		public static double ToFluidOunces(double value) => value / 0.0000284130742437499946;
		public static double ToUSTeaspoons(double value) => value / 0.000004928921593749999;
		public static double ToUSTablespoons(double value) => value / 0.000014786764781249998;
		public static double ToUSQuarts(double value) => value / 0.000946352945999999959;
		public static double ToUSPints(double value) => value / 0.000473176472999999979;
		public static double ToUSGallons(double value) => value / 0.003785411784;
		public static double ToUSFluidOunces(double value) => value / 0.0000295735296;
		public static double ToUSCups(double value) => value / 0.000236588236499999989;
	}
	public static class Litres
	{
		public static double ToMillilitres(double value) => value * 1000.0;
		public static double ToKilolitres(double value) => value / 1000.0;
		public static double ToTeaspoons(double value) => value / 0.005919390467447916134;
		public static double ToTablespoons(double value) => value / 0.017758171402343747584;
		public static double ToQuarts(double value) => value / 1.13652296975;
		public static double ToPints(double value) => value / 0.56826148487499988992;
		public static double ToGallons(double value) => value / 4.546091879;
		public static double ToFluidOunces(double value) => value / 0.028413074243749994496;
		public static double ToUSTeaspoons(double value) => value / 0.004928921593749999616;
		public static double ToUSTablespoons(double value) => value / 0.014786764781249998848;
		public static double ToUSQuarts(double value) => value / 0.94635294599999995904;
		public static double ToUSPints(double value) => value / 0.47317647299999997952;
		public static double ToUSGallons(double value) => value / 3.785411784;
		public static double ToUSFluidOunces(double value) => value / 0.029573529562499997696;
		public static double ToUSCups(double value) => value / 0.23658823649999998976;
	}
	public static class Millilitres
	{
		public static double ToLitres(double value) => value / 1000.0;
		public static double ToKilolitres(double value) => value / 1000000.0;
		public static double ToTeaspoons(double value) => value / 5.9193904674479161344;
		public static double ToTablespoons(double value) => value / 17.758171402343747584;
		public static double ToQuarts(double value) => value / 1136.52296975;
		public static double ToPints(double value) => value / 568.26148487499988992;
		public static double ToGallons(double value) => value / 4546.091879;
		public static double ToFluidOunces(double value) => value / 28.413074243749994496;
		public static double ToUSTeaspoons(double value) => value / 4.928921593749999616;
		public static double ToUSTablespoons(double value) => value / 14.786764781249998848;
		public static double ToUSQuarts(double value) => value / 946.35294599999995904;
		public static double ToUSPints(double value) => value / 473.17647299999997952;
		public static double ToUSGallons(double value) => value / 3785.411784;
		public static double ToUSFluidOunces(double value) => value / 29.573529562499997696;
		public static double ToUSCups(double value) => value / 236.58823649999998976;
	}
	public static class Pints
	{
		public static double ToMillilitres(double value) => value * 568.26148487499988992;
		public static double ToLitres(double value) => value * 0.56826148487499988992;
		public static double ToKilolitres(double value) => value * 0.000568261484874999889;
		public static double ToTeaspoons(double value) => value * 96.0;
		public static double ToTablespoons(double value) => value * 32.0;
		public static double ToQuarts(double value) => value  / 2.0;
		public static double ToGallons(double value) => value / 8.0;
		public static double ToFluidOunces(double value) => value * 20.0;
		public static double ToUSTeaspoons(double value) => value / 0.008673685838191568486;
		public static double ToUSTablespoons(double value) => value / 0.026021057514574708736;
		public static double ToUSQuarts(double value) => value / 1.6653476809327814656;
		public static double ToUSPints(double value) => value / 0.83267384046639071232;
		public static double ToUSGallons(double value) => value / 6.6613907237311258624;
		public static double ToUSFluidOunces(double value) => value / 0.052042115029149417472;
		public static double ToUSCups(double value) => value / 0.41633692023319535616;
	}
	public static class Quarts
	{
		public static double ToMillilitres(double value) => value * 1136.52296975;
		public static double ToLitres(double value) => value * 1.13652296975;
		public static double ToKilolitres(double value) => value * 0.00113652296975;
		public static double ToTeaspoons(double value) => value * 192.0;
		public static double ToTablespoons(double value) => value * 64.0;
		public static double ToPints(double value) => value * 2.0;
		public static double ToGallons(double value) => value / 4.0;
		public static double ToFluidOunces(double value) => value * 40.0;
		public static double ToUSTeaspoons(double value) => value / 0.004336842919095784243;
		public static double ToUSTablespoons(double value) => value / 0.013010528757287354368;
		public static double ToUSQuarts(double value) => value / 0.83267384046639071232;
		public static double ToUSPints(double value) => value / 0.41633692023319535616;
		public static double ToUSGallons(double value) => value / 3.3306953618655629312;
		public static double ToUSFluidOunces(double value) => value / 0.026021057514574708736;
		public static double ToUSCups(double value) => value / 0.20816846011659767808;
	}
	public static class Tablespoons
	{
		public static double ToMillilitres(double value) => value * 17.758171402343747584;
		public static double ToLitres(double value) => value * 0.017758171402343747584;
		public static double ToKilolitres(double value) => value * 0.000017758171402343747;
		public static double ToTeaspoons(double value) => value * 3.0;
		public static double ToQuarts(double value) => value / 64.0;
		public static double ToPints(double value) => value / 32.0;
		public static double ToGallons(double value) => value / 256.0;
		public static double ToFluidOunces(double value) => value / 1.6;
		public static double ToUSTeaspoons(double value) => value / 0.27755794682213023744;
		public static double ToUSTablespoons(double value) => value / 0.83267384046639071232;
		public static double ToUSQuarts(double value) => value / 53.291125789849001984;
		public static double ToUSPints(double value) => value / 26.645562894924500992;
		public static double ToUSGallons(double value) => value / 213.16450315939602432;
		public static double ToUSFluidOunces(double value) => value / 1.6653476809327814656;
		public static double ToUSCups(double value) => value / 13.322781447462250496;
	}
	public static class Teaspoons
	{
		public static double ToMillilitres(double value) => value * 5.9193904674479161344;
		public static double ToLitres(double value) => value * 0.005919390467447916134;
		public static double ToKilolitres(double value) => value * 0.000005919390467447916;
		public static double ToTablespoons(double value) => value / 3.0;
		public static double ToQuarts(double value) => value / 192.0;
		public static double ToPints(double value) => value / 96.0;
		public static double ToGallons(double value) => value / 768.0;
		public static double ToFluidOunces(double value) => value / 4.8;
		public static double ToUSTeaspoons(double value) => value / 0.83267384046639071232;
		public static double ToUSTablespoons(double value) => value / 2.4980215213991718912;
		public static double ToUSQuarts(double value) => value / 159.87337736954701824;
		public static double ToUSPints(double value) => value / 79.936688684773507072;
		public static double ToUSGallons(double value) => value / 639.49350947818807296;
		public static double ToUSFluidOunces(double value) => value / 4.9960430427983437824;
		public static double ToUSCups(double value) => value / 39.968344342386753536;
	}
	public static class USCups
	{
		public static double ToMillilitres(double value) => value * 236.58823649999998976;
		public static double ToLitres(double value) => value * 0.23658823649999998976;
		public static double ToKilolitres(double value) => value * 0.000236588236499999989;
		public static double ToTeaspoons(double value) => value * 39.968344342386753536;
		public static double ToTablespoons(double value) => value * 13.322781447462250496;
		public static double ToQuarts(double value) => value * 0.20816846011659767808;
		public static double ToPints(double value) => value * 0.41633692023319535616;
		public static double ToGallons(double value) => value * 0.052042115029149417472;
		public static double ToFluidOunces(double value) => value * 8.3267384046639071232;
		public static double ToUSTeaspoons(double value) => value * 48.0;
		public static double ToUSTablespoons(double value) => value * 16.0;
		public static double ToUSQuarts(double value) => value / 4.0;
		public static double ToUSPints(double value) => value / 2.0;
		public static double ToUSGallons(double value) => value / 16.0;
		public static double ToUSFluidOunces(double value) => value * 8.0;
	}
	public static class USFluidOunces
	{
		public static double ToMillilitres(double value) => value * 29.573529562499997696;
		public static double ToLitres(double value) => value * 0.029573529562499997696;
		public static double ToKilolitres(double value) => value * 0.0000295735296;
		public static double ToTeaspoons(double value) => value * 4.9960430427983437824;
		public static double ToTablespoons(double value) => value * 1.6653476809327814656;
		public static double ToQuarts(double value) => value * 0.026021057514574708736;
		public static double ToPints(double value) => value * 0.052042115029149417472;
		public static double ToGallons(double value) => value * 0.006505264378643677184;
		public static double ToFluidOunces(double value) => value * 1.0408423005829883904;
		public static double ToUSTeaspoons(double value) => value * 6.0;
		public static double ToUSTablespoons(double value) => value * 2.0;
		public static double ToUSQuarts(double value) => value / 32.0;
		public static double ToUSPints(double value) => value / 16.0;
		public static double ToUSGallons(double value) => value / 128.0;
		public static double ToUSCups(double value) => value / 8.0;
	}
	public static class USGallons
	{
		public static double ToMillilitres(double value) => value * 3785.411784;
		public static double ToLitres(double value) => value * 3.785411784;
		public static double ToKilolitres(double value) => value * 0.003785411784;
		public static double ToTeaspoons(double value) => value * 639.49350947818807296;
		public static double ToTablespoons(double value) => value * 213.16450315939602432;
		public static double ToQuarts(double value) => value * 3.3306953618655629312;
		public static double ToPints(double value) => value * 6.6613907237311258624;
		public static double ToGallons(double value) => value * 0.83267384046639071232;
		public static double ToFluidOunces(double value) => value * 133.22781447462252544;
		public static double ToUSTeaspoons(double value) => value * 768.0;
		public static double ToUSTablespoons(double value) => value * 256.0;
		public static double ToUSQuarts(double value) => value * 4.0;
		public static double ToUSPints(double value) => value * 8.0;
		public static double ToUSFluidOunces(double value) => value * 128.0;
		public static double ToUSCups(double value) => value * 16.0;
	}
	public static class USPints
	{
		public static double ToMillilitres(double value) => value * 473.17647299999997952;
		public static double ToLitres(double value) => value * 0.47317647299999997952;
		public static double ToKilolitres(double value) => value * 0.000473176472999999979;
		public static double ToTeaspoons(double value) => value * 79.936688684773507072;
		public static double ToTablespoons(double value) => value * 26.645562894924500992;
		public static double ToQuarts(double value) => value * 0.41633692023319535616;
		public static double ToPints(double value) => value * 0.83267384046639071232;
		public static double ToGallons(double value) => value * 0.10408423005829883904;
		public static double ToFluidOunces(double value) => value * 16.653476809327814656;
		public static double ToUSTeaspoons(double value) => value * 96.0;
		public static double ToUSTablespoons(double value) => value * 32.0;
		public static double ToUSQuarts(double value) => value / 2.0;
		public static double ToUSGallons(double value) => value / 8.0;
		public static double ToUSFluidOunces(double value) => value * 16.0;
		public static double ToUSCups(double value) => value * 2.0;
	}
	public static class USQuarts
	{
		public static double ToMillilitres(double value) => value * 946.35294599999995904;
		public static double ToLitres(double value) => value * 0.94635294599999995904;
		public static double ToKilolitres(double value) => value * 0.000946352945999999959;
		public static double ToTeaspoons(double value) => value * 159.87337736954701824;
		public static double ToTablespoons(double value) => value * 53.291125789849001984;
		public static double ToQuarts(double value) => value * 0.83267384046639071232;
		public static double ToPints(double value) => value * 1.6653476809327814656;
		public static double ToGallons(double value) => value * 0.20816846011659767808;
		public static double ToFluidOunces(double value) => value * 33.306953618655629312;
		public static double ToUSTeaspoons(double value) => value * 192.0;
		public static double ToUSTablespoons(double value) => value * 64.0;
		public static double ToUSPints(double value) => value * 2.0;
		public static double ToUSGallons(double value) => value / 4.0;
		public static double ToUSFluidOunces(double value) => value * 32.0;
		public static double ToUSCups(double value) => value * 4.0;
	}
	public static class USTablespoons
	{
		public static double ToMillilitres(double value) => value * 14.786764781249998848;
		public static double ToLitres(double value) => value * 0.014786764781249998848;
		public static double ToKilolitres(double value) => value * 0.000014786764781249998;
		public static double ToTeaspoons(double value) => value * 2.4980215213991718912;
		public static double ToTablespoons(double value) => value * 0.83267384046639071232;
		public static double ToQuarts(double value) => value * 0.013010528757287354368;
		public static double ToPints(double value) => value * 0.026021057514574708736;
		public static double ToGallons(double value) => value * 0.003252632189321838592;
		public static double ToFluidOunces(double value) => value * 0.52042115029149417472;
		public static double ToUSTeaspoons(double value) => value * 3.0;
		public static double ToUSQuarts(double value) => value / 64.0;
		public static double ToUSPints(double value) => value / 32.0;
		public static double ToUSGallons(double value) => value / 256.0;
		public static double ToUSFluidOunces(double value) => value / 2.0;
		public static double ToUSCups(double value) => value / 16.0;
	}
	public static class USTeaspoons
	{
		public static double ToMillilitres(double value) => value * 4.928921593749999616;
		public static double ToLitres(double value) => value * 0.004928921593749999616;
		public static double ToKilolitres(double value) => value * 0.000004928921593749999;
		public static double ToTeaspoons(double value) => value * 0.83267384046639071232;
		public static double ToTablespoons(double value) => value * 0.27755794682213023744;
		public static double ToQuarts(double value) => value * 0.004336842919095784243;
		public static double ToPints(double value) => value * 0.008673685838191568486;
		public static double ToGallons(double value) => value * 0.00108421072977394606;
		public static double ToFluidOunces(double value) => value * 0.1734737167638313984;
		public static double ToUSTablespoons(double value) => value / 3.0;
		public static double ToUSQuarts(double value) => value / 192.0;
		public static double ToUSPints(double value) => value / 96.0;
		public static double ToUSGallons(double value) => value / 768.0;
		public static double ToUSFluidOunces(double value) => value / 6.0;
		public static double ToUSCups(double value) => value / 48.0;
	}
}
